apiBaseUrl: https://api.tray.io
sourceProjectId: efcd5c47-85ad-4114-a367-f76b42df6966
destinationProjectId: 9718ee38-3eea-47a8-81c5-88d802706d08
sourceVersion: latest
scope: platform
# To deploy embedded, uncomment the line below and change the above scope to platform-and-solutions
# solutionId: 33333333-3333-3333-3333-333333333333
failOnBreakingChanges: true
authMappings:
  - authExportId: salesforce-1
    authenticationId: d5bdfa22-95cc-4cd4-84dc-ca15aa2a733a
